name: ci-tethys-store-test
on:
    push:
        branches:
            - master
        paths-ignore:
            - README.md
            - CHANGELOG.md # Should never be edited anyway
            - .gitignore
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - name: Use Node.js 24.x
              uses: actions/setup-node@v4
              with:
                  node-version: 24.x
                  cache: pnpm
            - name: Setup
              run: pnpm install --frozen-lockfile

            - name: Test
              run: |
                  pnpm lint
                  pnpm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
                  pnpm run report-coverage
